conky.config = {
	own_window = true,
	own_window_class = 'Conky',
	own_window_type = 'normal',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	own_window_transparent = true ,
	own_window_argb_visual = true ,
	own_window_argb_value = 0 ,
	draw_blended = false ,
	update_interval = 1 ,
	lua_load = '~/.config/conky/clock.lua',
	use_xft = true ,

	xinerama_head = 0 ,
	alignment = 'top_middle',

	minimum_width = 205 ,
	maximum_height = 45 ,

    update_interval = 1 ,
    double_buffer = true ,
    default_color = 'ffffff' ,

    font_dir = '/home/cccp/.config/conky/' ,
};

conky.text = [[
${lua_parse conky_show_digit 1}
${lua_parse conky_show_digit 2}
${lua_parse conky_show_digit 3}
${lua_parse conky_show_digit 4}
#${lua_parse conky_show_digit 5}
#${lua_parse conky_show_digit 6}
${voffset -75}${goto 100}${font PixelOperator.ttf:size=35}:${font}\
${voffset -60}
]];
