[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/microcai/gentoo-zh.git

[palemoon]
location = /var/db/repos/palemoon
sync-type = git
sync-uri = https://github.com/deu/palemoon-overlay.git

[librewolf]
priority = 50
location = /var/db/repos/librewolf
sync-type = git
sync-uri = https://codeberg.org/librewolf/gentoo.git
auto-sync = Yes

[uniminin-overlay]
location = /var/db/repos/uniminin-overlay
sync-type = git
sync-uri = https://github.com/loannaflip/overlay.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[local]
location = /var/db/repos/local

[overlay-from-plan9]
location = /var/db/repos/overlay-from-plan9
sync-type = git
sync-uri = https://gitea.com/catfromplan9/overlay-from-plan9
